name: Build Applications

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        arch: [ arm64, x64 ]
    runs-on: macos-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build React App
        run: pnpm build

      - name: Build Electron App for macOS (${{ matrix.arch }})
        run: pnpm exec electron-builder --mac --${{ matrix.arch }} --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build React App
        run: pnpm build

      - name: Build Electron App for Windows
        run: pnpm exec electron-builder --win --x64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
